### ISSUE TITLE
rtx panics

### ISSUE THREAD

**Issue by jankatins** [jdxcode/rtx#103] opened 2023-02-04 21:13 UTC
I'm running `rtx x python@3.11 -- python3 -m venv .` (version: `rtx 1.5.0 (built 2023-02-04)`)in a bootstrap script (bash, calls more bash scripts which calls rtx; the main script exports some functions to make them available in the called additional bash scripts; not sure if the latter is interesting) and this ended up with:

```
The application panicked (crashed).
Message:  failed to set environment variable `""` to `""`: Invalid argument (os error 22)
Location: library/std/src/env.rs:353

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 8 frames hidden ⋮
   9: std::env::_set_var::h6ff1976ef2d27892
      at <unknown source file>:<unknown line>
  10: <rtx::cli::exec::Exec as rtx::cli::command::Command>::run::h2d8bb112ad83bad8
      at <unknown source file>:<unknown line>
  11: rtx::cli::Cli::run::hd3b4bd09e4c19951
      at <unknown source file>:<unknown line>
  12: rtx::main::h346c180a454697a7
      at <unknown source file>:<unknown line>
  13: std::sys_common::backtrace::__rust_begin_short_backtrace::hd33f4d5347a9674e
      at <unknown source file>:<unknown line>
  14: std::rt::lang_start::{{closure}}::h7a55c4bdb7cc3632
      at <unknown source file>:<unknown line>
  15: std::rt::lang_start_internal::hd56d2fa7efb2dd60
      at <unknown source file>:<unknown line>
  16: _main<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
!!! ERROR !!! Script 8-py-venv-environments errored, aborting....
```

Not sure if this is relevant, but for completeness:

```
function exit_if_not_debian() {
  [[ "${YADM_BOOTSTRAP_DISTRO}" != 'debian' ]] && msg "Not Debian, Bye!" && exit
}
export -f exit_if_not_debian
```

A exported function ends up as this when printed with `env` straight before the script:

```
BASH_FUNC_exit_if_not_debian%%=() {  [[ "${YADM_BOOTSTRAP_DISTRO}" != 'debian' ]] && msg "Not Debian, Bye!" && exit
}
```

**Comment by jdxcode** [comment] 2023-02-04 21:44
based on that error I suspect rtx is detecting an empty environment variable and trying to set an environment variable to that. It may not be an empty environment variable, it could be something that's getting stripped with `.to_lossy_string()` somewhere. I'll do some digging to see what's going on.

If you can manage to run the code yourself and you added a [trace line](https://github.com/jdxcode/rtx/blob/main/src/cli/exec.rs#L66) here you might be able to get more information.

**Comment by jdxcode** [comment] 2023-02-04 21:55
That exported function does sound suspect. I'm not really sure where it could be getting into rtx though since asdf-python doesn't have an exec-env script

**Comment by jankatins** [comment] 2023-02-04 22:01
The exported fun seems to be the problem: the below crashes unless I comment out the `export -f exit_if_not_debian` line.

```bash
#!/bin/bash
function exit_if_not_debian() {
  printf "Not Debian, Bye!" && exit
}
# Comment the next line to not crash
export -f exit_if_not_debian
rtx x python@3.11 -- python3 --version
```

**Comment by jdxcode** [comment] 2023-02-04 22:10
Which other plugins do you have installed? I bet you have one with an exec-env script. That script is probably fine but rtx tries to read all exported env vars when it run. I didn't account for env vars that aren't strings.

**Comment by jankatins** [comment] 2023-02-04 23:02
I'm using rtx (since today...) with rust and python, if that is what you mean with "plugins".

**Comment by jdxcode** [comment] 2023-02-05 00:08
hmm I'm having a little trouble reproducing this:

```
bash-5.2$ function exit_if_not_debian() {   printf "Not Debian, Bye!" && exit; }
bash-5.2$ rtx -V
rtx 1.5.0 (built 2023-02-04)
bash-5.2$ rtx exec python@3.11 -- python -V
Python 3.11.1
bash-5.2$ BASH_FUNC_exit_if_not_debian%%=() {  [[ "${YADM_BOOTSTRAP_DISTRO}" != 'debian' ]] && msg "Not Debian, Bye!" && exit; }
bash-5.2$ rtx exec python@3.11 -- python -V
Python 3.11.1
```

any tips on what I might be doing differently? I'm not familiar with that BASH_FUNC stuff so not sure if I'm missing a step.

**Comment by jankatins** [comment] 2023-02-05 00:12
```bash
bash-3.2$ function exit_if_not_debian() {   printf "Not Debian, Bye" && exit; }
bash-3.2$ rtx exec python@3.11 -- python -V
Python 3.11.1
bash-3.2$ export -f exit_if_not_debian
bash-3.2$ rtx exec python@3.11 -- python -V
The application panicked (crashed).
Message:  failed to set environment variable `""` to `""`: Invalid argument (os error 22)
Location: library/std/src/env.rs:353

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by jdxcode** [comment] 2023-02-05 00:13
oh right, of course, that did it, I got the same output

**Comment by jdxcode** [comment] 2023-02-05 00:18
this will be fixed in the next release: https://github.com/jdxcode/rtx/commit/69e17aa0e3fb49f5d6f0fe631a0062a807a6dcbc

for now you can either remove it or remove the rust plugin

**Closed** 2023-02-05 00:17 UTC

**Comment by jankatins** [comment] 2023-02-05 00:22
Wow, thanks! I will simply wait for the next release for now and then rerun the bootstrap script of mine :-)
