### ISSUE TITLE
slow 1 minute shell startup on vpn, due to block network connection

### ISSUE THREAD

**Issue by alejandroMA** [jdxcode/rtx#539] opened 2023-05-11 21:01 UTC
**Describe the bug**
The shell takes 75 secs or more to start up when I'm connected to my corporate vpn, and when it finally does it shows the following message:

> [WARN] failed to resolve tool version: git failed: ["-C", "/Users/madariaga/Library/Caches/rtx/node/node-build", "fetch", "--prune", "--update-head-ok", "origin", "master:master"] fatal: unable to access 'https://github.com/nodenv/node-build.git/': Failed to connect to github.com port 443 after 75101 ms: Couldn't connect to server

**To Reproduce**
I installed rtx with home brew ,and right now i'm only using it to manage node.js

1. Install rtx via homebrew
2. run `echo 'eval "$(/opt/homebrew/bin/rtx activate zsh)" ' >> ~/.zshrc`
3. run `rtx install node@18`
4. run `rtx use -g node@18`
5. restart the computer
6. connect to vpn (or block the network request some other way)
7.  open a shell window, (the problem should occur)
8.  open another shell, (the problem will happen again)

**Expected behavior**

It would be best if no network connections were made when the shell is opened, or at least have a smaller timeout say 5 sec

**`rtx doctor` output**

```
rtx version:
  1.29.6 macos-arm64 (unknown 2023-05-07)

build:
  Target: aarch64-apple-darwin
  Features: BREW
  Built: Sun, 07 May 2023 16:20:09 +0000
  Rust Version: rustc 1.69.0 (84c898d65 2023-04-16) (built from a source tarball)
  Profile: release

shell:
  /bin/zsh
  zsh 5.9 (x86_64-apple-darwin22.0)

rtx environment variables:
  RTX_SHELL=zsh

settings:
  {"experimental": "false", "missing_runtime_behavior": "warn", "always_keep_download": "false", "always_keep_install": "false", "legacy_version_file": "true", "plugin_autoupdate_last_check_duration": "10080", "trusted_config_paths": "[]", "verbose": "false", "asdf_compat": "false", "jobs": "4", "disable_default_shorthands": "false", "log_level": "INFO", "raw": "false"}

config files:
  /Users/madariaga/.config/rtx/config.toml

plugins:
  node   (core)

toolset:
  node@18

No problems found
```

**Additional context**
I think a current workaround is to open a shell before connecting to the vpn

**Comment by jdxcode** [comment] 2023-05-14 18:47
Hmm I think there are a couple of things I need to check here. First, if the user isn't using node at all then this shouldn't even attempt a fetch (I'm not sure if that is the case or not, will need to verify). It could be an issue though since node is a core plugin and you can't really opt-out if it.

Of course I can add a timeout when running this git fetch but that's tricky. I think what I would prefer is making the CLI not block on this if possible at least in some cases.

In any case, I need to do a deeper dive here. In the meantime, I'd accept a PR to reduce the timeout to 10 seconds I think. If I have time I'll try to add this myself but it's going to be an extremely busy week for me.

**Comment by khimaros** [comment] 2023-05-15 18:43
it would be great to at least have a setting to disable the automatic git fetch. i'm also running into this issue when working from areas without internet.

**Comment by jdxcode** [comment] 2023-05-15 21:49
We don't need a setting here I don't think, there shouldn't be a need to fetch latest versions except on some commands like `rtx install`, `rtx latest`, and `rtx ls-remote`. If you're just using rtx in your shell with `rtx activate` it shouldn't have a need to fetch versions I don't think. So this feels like a bug.

**Comment by khimaros** [comment] 2023-05-15 22:22
@jdxcode seems reasonable to me. let me know if you'd like any additional information to help troubleshoot or reproduce. it happens consistently for me with the following config:

```toml
[tools]
python = "3.9"
node = "12"
```

```shell
$ rtx current
python 3.9.16
node 12.22.12
```

**Comment by jdxcode** [comment] 2023-05-23 00:32
I added #577 which drops the timeout to 10s but also makes it configurable so you can set it to 0 seconds `RTX_FETCH_REMOTE_VERSIONS_TIMEOUT=0s` if you don't want it to check at all.

**Comment by jdxcode** [comment] 2023-05-23 00:33
I'm going to leave this open since I still think this should be better handled

**Comment by khimaros** [comment] 2023-06-03 17:50
@jdxcode thank you for doing this! just curious how do env vars intersect with `rtx settings`? is there also a way to configure this in settings or is env var the only way?

**Comment by jdxcode** [comment] 2023-07-14 17:09
env var is the only way currently, we could move it to a setting, maybe open up a separate issue for that.

**Comment by jdxcode** [comment] 2023-07-20 16:10
the version check is removed so I am closing this

**Closed by jdxcode** 2023-07-20 16:10 UTC
Labels: bug
