### ISSUE TITLE
Setting of asdf-plugin environment variables inconsistent

### ISSUE THREAD

**Issue by amoosbr** [jdxcode/rtx#47] opened 2023-01-30 09:22 UTC
I tested the environment variables a bit more using `rtx 1.2.6` and found some unexpected behavior while using them.

**Using `eval "$(rtx activate -s zsh)"` in a new zsh session (no direnv):**

1. All environment variables unset/empty, when switching to a new directory without .tool-versions

```sh
# initially all environment variables are set as expected
❯ echo $RUBYLIB
/Users/user/.local/share/rtx/plugins/ruby/rubygems-plugin
❯ echo $GOROOT
/Users/user/.local/share/rtx/installs/golang/1.19.5/go
❯ echo $JAVA_HOME
/Users/user/.local/share/rtx/installs/java/temurin-17.0.5+8

# Issue: All environment variables unset/empty, when switching to a new directory
# Expected: All environment variables have the same value as above
# `~/dev` doesn't contain a .tool-versions file

❯ cd ~/dev
❯ echo $RUBYLIB

❯ echo $JAVA_HOME

❯ echo $GOROOT

```

2. RUBYLIB unset in directory containing a local .tool-versions file -> This might be no real issues with rtx, as RUBYLIB seems to contain only a file needed for asdf related reshimming, when installing a rubygem file with an executable. But perhaps it is still relevant to understand the behavior.

```sh
# initially all environment variables are set as expected
❯ echo $GOROOT
/Users/user/.local/share/rtx/installs/golang/1.19.5/go
❯ echo $JAVA_HOME
/Users/user/.local/share/rtx/installs/java/temurin-17.0.5+8
❯ echo $RUBYLIB
/Users/user/.local/share/rtx/plugins/ruby/rubygems-plugin

# switching directory

❯ cd ~/dev/tmp/rtx-env-variables
❯ cat .tool-versions
java temurin-11.0.15+10
golang 1.18.1
ruby 3.0.5

# all environment variables besides RUBYLIB set to new values. RUBYLIB is unset. Not sure, if this is on purpose the same in asdf.
# Expected: RUBYLIB still set (?)

❯ echo $GOROOT
/Users/user/.local/share/rtx/installs/golang/1.18.10/go
❯ echo $JAVA_HOME
/Users/user/.local/share/rtx/installs/java/temurin-11.0.15+10
❯ echo $RUBYLIB

# again, when traversing to a subdirectory all environment variables are unset. But this time RUBYLIB is unexpectedly set now
# Expected: All environment variables set to the values of nearest local .tool-versions

❯ mkdir test
❯ cd test
❯ echo $GOROOT

❯ echo $JAVA_HOME

❯ echo $RUBYLIB
/Users/user/.local/share/rtx/plugins/ruby/rubygems-plugin

# for completeness, the value when switching back to the previous directory

❯ cd ..
❯ echo $GOROOT
/Users/user/.local/share/rtx/installs/golang/1.18.10/go
❯ echo $JAVA_HOME
/Users/user/.local/share/rtx/installs/java/temurin-11.0.15+10
❯ echo $RUBYLIB

```

**Using `eval "$(rtx env -s zsh)"` in a new zsh session in combination with `use rtx` in direnv:**

1. GOROOT not updated and RUBYLIB concatenated to incorrect value 

```sh
# initially all environment variables are set as expected

❯ echo $GOROOT
/Users/user/.local/share/rtx/installs/golang/1.19.5/go
❯ echo $JAVA_HOME
/Users/user/.local/share/rtx/installs/java/temurin-17.0.5+8
❯ echo $RUBYLIB
/Users/user/.local/share/rtx/plugins/ruby/rubygems-plugin

# switching to a project folder managed by direnv

❯ cd ~/dev/tmp/rtx-env-variables-direnv
direnv: loading ~/Projects/tmp/rtx-env-variables-direnv/.envrc
direnv: using rtx
direnv: export ~JAVA_HOME ~PATH ~RUBYLIB

# Expected: GOROOT set to 1.18.1 and not unchanged
# Is set correctly for JAVA_HOME

❯ echo $GOROOT
/Users/user/.local/share/rtx/installs/golang/1.19.5/go
❯ echo $JAVA_HOME
/Users/user/.local/share/rtx/installs/java/temurin-11.0.15+10

# Expected: RUBYLIB value set to `/Users/user/.local/share/rtx/plugins/ruby/rubygems-plugin` and not concatenated

❯ echo $RUBYLIB
/Users/user/.local/share/rtx/plugins/ruby/rubygems-plugin:/Users/user/.local/share/rtx/plugins/ruby/rubygems-plugin

# folder setup

❯ cat .envrc
use rtx

❯ cat .tool-versions
java temurin-11.0.15+10
golang 1.18.1
ruby 3.0.5

❯ rtx local
java temurin-11.0.15+10
golang 1.18.1
ruby 3.0.5
❯ go version
go version go1.18.10 darwin/arm64
❯ java --version
openjdk 11.0.15 2022-04-19
OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)
❯ ruby --version
ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [arm64-darwin22]
```

**Comment by jdxcode** [comment] 2023-01-30 14:45
1. I do not understand why you would expect this behavior. If rtx is in a directory without a .tool-versions file it should be as if rtx wasn't being used. Maybe you can explain more why you would want this.
2. I think I know what is happening here. It think that `$RUBYLIB` hasn't changed because the value isn't different from what it was before. It should compare the environment variable to what the env vars _will_ be after the ones from the old directory are cleared out.
3. These languages behave differently because their plugins are different.

In ruby, it appends the old RUBYLIB onto the new one: https://github.com/asdf-vm/asdf-ruby/blob/master/bin/exec-env. In go, it does not set `GOPATH` if it already exists: https://github.com/kennyp/asdf-golang/blob/master/bin/exec-env.

Normally if using `hook-env` this isn't a problem since the environment variables are supposed to be cleared out before running these. However when you use `rtx env` with the direnv hook, `rtx` doesn't know that the env vars were set because of its own `rtx env`.

I might need to set `__RTX_DIFF` when using `rtx env`. Or maybe you could call `rtx hook-env` instead of `rtx env`. That will use the same stuff that activate calls but only a single time.

**Comment by amoosbr** [comment] 2023-01-30 15:15
1. I try to explain why I would expect the behavior in 1.

If I have a global `~/.tools-version` file that fits most of my requirements regarding the tools.
And I have an executable `x` expecting JAVA_HOME or GOROOT to be set, I would need to call `x` from `~/`. If I would call it from any subfolder like `cd ~/something` (not containing its own .tool-versions file) then call `x` the environment variables would not be set.
The same goes for a project containing a `.tool-versions` file in the root folder of the project. I would only be able to call tools expecting the environment variables set, when in this project root folder. Calling from a project subfolder wouldn't work.

Hope this helps. But might be my personal preference.

2. Ok, the environment variables managed by asdf-plugins sound more complicated than I hoped. Then the current behavior of rtx is probably correct.

I try if I can use the `rtx hook-env` call within the direnv `use rtx` call and see if this changes things.

**Comment by jdxcode** [comment] 2023-01-31 02:41
#2 (which I think was the worst out of these) is now fixed by https://github.com/jdxcode/rtx/commit/1e19108b494b499acbead5f77dbdcfafac95b36b

**Comment by jdxcode** [comment] 2023-01-31 04:33
the way you described 1 sounds more problematic than I first realized, I didn't realize this was working in subdirectories where they share the same ancestor.

If you were so inclined, one thing that would be unbelievably helpful is if you could write any of these cases down as an E2E test (which doesn't have to actually function), here is a good example to see how they work: https://github.com/jdxcode/rtx/blob/main/e2e/gopath/test_gopath. That runs from the directory that it is in, so it uses [this `.tool-versions` file](https://github.com/jdxcode/rtx/blob/main/e2e/gopath/.tool-versions). Most of the time it takes for me to resolve these is just figuring out how to reproduce them.

**Comment by jdxcode** [comment] 2023-01-31 04:34
the way you described 1 sounds more problematic than I first realized, I didn't realize this was working in subdirectories where they share the same ancestor. I'll have to dig into this more.

If you were so inclined, one thing that would be unbelievably helpful is if you could write any of these cases down as an E2E test (which doesn't have to actually function), here is a good example to see how they work: https://github.com/jdxcode/rtx/blob/main/e2e/gopath/test_gopath. That runs from the directory that it is in, so it uses [this `.tool-versions` file](https://github.com/jdxcode/rtx/blob/main/e2e/gopath/.tool-versions). Most of the time it takes for me to resolve these is just figuring out how to reproduce them.

**Comment by amoosbr** [comment] 2023-01-31 07:27
Did a retest with `rtx v1.2.7`.
I confirm, that 2 is working for me as well. But by fixing 2, you also fixed 1 🎉. Seems it was the same bug.

```sh
❯ echo $GOROOT
/Users/user/.local/share/rtx/installs/golang/1.19.5/go
❯ echo $JAVA_HOME
/Users/user/.local/share/rtx/installs/java/temurin-17.0.6+10
❯ echo $RUBYLIB
/Users/user/.local/share/rtx/plugins/ruby/rubygems-plugin

# switch to subdirectory with same .tool-versions ancestor
# plugin environment variables still set

❯ cd ~/dev
❯ echo $GOROOT
/Users/user/.local/share/rtx/installs/golang/1.19.5/go
❯ echo $JAVA_HOME
/Users/user/.local/share/rtx/installs/java/temurin-17.0.6+10
❯ echo $RUBYLIB
/Users/user/.local/share/rtx/plugins/ruby/rubygems-plugin
```

Sub-issue 3 is related to the way, rtx needs to be used in combination with direnv today. As you are working on improvements there, I would say we can ignore this for now and close the issue.

Regarding the e2e test, I will have a look at your links and try to create test cases next time I find an issue.
I'm really impressed by your work on rtx. Thank you

**Comment by jdxcode** [comment] 2023-02-01 01:46
I'm going to close this in favor of #8

**Closed by jdxcode** 2023-02-01 01:46 UTC
Labels: bug
