### ISSUE TITLE
Unable to auto-complete plugin names and/or version numbers

### ISSUE THREAD

**Issue by x80486** [jdxcode/rtx#673] opened 2023-07-11 20:36 UTC
## Description

I just installed `rtx`. While I install applications/binaries I would expect `rtx` to be able to:

- Retrieve the version numbers from the plugin in question when installing
- Resolve the version number of the already installed application/binary

All of that when hitting <kbd>Tab</kbd> for auto-completion.

## To Reproduce

- Install `rtx` — I used the `Nix` package (under `Arch Linux`)
- `rtx install java ...` ― those `...` means "hit <kbd>Tab</kbd>" (several times if needed)

...and assuming a `java` version is installed:

- `rtx global java@...` ― those `...` means "hit <kbd>Tab</kbd>" (several times if needed)

## Expected Behavior

`rtx` to be able to retrieve the version numbers from the plugin in question when installing; or when a given plugin is installed already and try to add it to the global/local configuration, `rtx` to be able to resolve the version number.

**`rtx doctor` output**

```
[x80486@uplink:~]$ rtx doctor 
rtx version:
  1.32.2 linux-x64 (unknown 2023-07-06)

build:
  Target: x86_64-unknown-linux-gnu
  Features: 
  Built: Thu, 06 Jul 2023 14:43:07 +0000
  Rust Version: rustc 1.70.0 (90c541806 2023-05-31) (built from a source tarball)
  Profile: release

shell:
  /bin/bash
  GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
  Copyright (C) 2020 Free Software Foundation, Inc.
  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

  This is free software; you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.

rtx environment variables:
  RTX_CONFIG_FILE=/home/x80486/.config/rtx/config.toml
  RTX_SHELL=bash

settings:
  {"always_keep_download": "false", "always_keep_install": "false", "asdf_compat": "false", "disable_default_shorthands": "false", "disable_tools": "[]", "experimental": "false", "jobs": "4", "legacy_version_file": "false", "legacy_version_file_disable_tools": "[]", "log_level": "INFO", "missing_runtime_behavior": "warn", "plugin_autoupdate_last_check_duration": "0", "raw": "false", "trusted_config_paths": "[]", "verbose": "false"}

config files:
  /home/x80486/.config/rtx/config.toml

plugins:
  bun      https://github.com/cometkim/asdf-bun.git#fd84edd
  go       https://github.com/rtx-plugins/rtx-golang.git#29068ac
  java     https://github.com/rtx-plugins/rtx-java.git#a8cbfc1
  node     (core)
  python   (core)

toolset:
  node@18, go@1.20, bun@0.6.13

No problems found
```

## Additional Context

I do have the completions (`rtx completion bash`) being sourced on `.bashrc`. I saved the output of the aforementioned command into a file, and I'm sourcing it within `.bashrc`.

**Comment by jdxcode** [comment] 2023-07-11 21:17
this is a duplicate of #97

**Closed** 2023-07-11 21:18 UTC
Labels: bug
